[tool.poetry]
name = "reworkd_platform"
version = "0.2.0"
description = "Modernized AgentGPT Platform"
authors = [
    "awtkns",
    "asim-shrestha"
]

maintainers = [
    "reworkd"
]

readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
fastapi = "^0.115.0"
boto3 = "^1.35.0"
uvicorn = { version = "^0.32.0", extras = ["standard"] }
pydantic = { version = "^2.10", extras = ["dotenv"] }
sqlalchemy = { version = "^2.0.36", extras = ["mypy", "asyncio"] }
aiomysql = "^0.2.0"
mysqlclient = "^2.2.4"
sentry-sdk = "^2.17.0"
loguru = "^0.7.2"
requests = "^2.32.0"
langchain = "^0.3.0"
langchain-core = "^0.3.0"
langchain-openai = "^0.2.0"
langchain-community = "^0.3.0"
openai = "^1.50.0"

replicate = "^0.30.0"
tiktoken = "^0.8.0"
pinecone-client = "^5.0.0"
python-multipart = "^0.0.12"
botocore = "^1.35.0"
cryptography = "^44.0.0"
httpx = "^0.28.0"
aiohttp = "^3.10.0"


[tool.poetry.group.dev.dependencies]
# Testing
pytest = "^8.3.0"
pytest-cov = "^6.0.0"
pytest-env = "^1.1.3"
pytest-mock = "^3.14.0"
pytest-asyncio = "^0.24.0"
# Linting & formatting
pre-commit = "^4.0.0"
autoflake = "^2.3.1"
flake8 = "~7.1.0"
isort = "^5.13.0"
wemake-python-styleguide = "^0.19.0"
black = "^24.10.0"
# Type checking
mypy = "^1.13.0"
types-requests = "^2.32.0"
types-pytz = "^2024.2.0"
# Misc
anyio = "^4.6.0"

[tool.isort]
profile = "black"
multi_line_output = 3
src_paths = ["reworkd_platform"]

[tool.mypy]
strict = true
ignore_missing_imports = true
allow_subclassing_any = true
allow_untyped_calls = true
pretty = true
show_error_codes = true
implicit_reexport = true
allow_untyped_decorators = true
warn_unused_ignores = false
warn_return_any = false
namespace_packages = true
exclude = "tests"

[tool.pytest.ini_options]
filterwarnings = [
    "error",
    "ignore::DeprecationWarning",
    "ignore:.*unclosed.*:ResourceWarning",
    "ignore::ImportWarning",
]
env = [
    "REWORKD_PLATFORM_DB_BASE=reworkd_platform_test",
]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
